apiVersion: apps/v1
kind: Deployment
metadata:
    name: xavictest-deployment
spec:
    selector:
        matchLabels:
            app: xavic-test
    replicas: 1
    template:
        metadata:
            labels:
                app: xavic-test
        spec:
            containers:
            -   name: xavic-test-container
                image: xavicampa/xavic-test:latest
                ports:
                - containerPort: 8080
                resources:
                    requests:
                        memory: "64Mi"
                        cpu: "250m"
                    limits:
                        memory: "128Mi"
                        cpu: "500m"